comment:
  layout: "header, diff, flags, components"

component_management:
  individual_components:
    - component_id: ts-microservice
      name: TypeScript microservice
      paths:
        - packages/microservice/src/**
    - component_id: rust-microservice
      name: Rust microservice
      paths:
        - crates/microservice/src/**
