comment:
    layout: 'header, diff, flags, components'

component_management:
    individual_components:
        - component_id: ts-application
          name: TypeScript application
          paths:
              - packages/application/src/**
        - component_id: rust-application
          name: Rust application
          paths:
              - crates/application/src/**
