import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	guidesSidebar: [
		'introduction',
		'installation',
		'quick-start',
		'core-concepts',
		{
			type: 'category',
			label: 'Guides',
			items: ['guides/module-lifecycle', 'guides/stopping-and-errors'],
		},
		'examples',
		'compatibility',
		{
			type: 'category',
			label: 'API reference',
			link: { type: 'doc', id: 'api' },
			items: [
				{
					type: 'category',
					label: 'TypeScript',
					items: [
						{
							type: 'category',
							label: '@microde/microservice',
							link: { type: 'doc', id: 'typescript-api' },
							items: [
								{
									type: 'autogenerated',
									dirName: 'api-reference',
								},
							],
						},
					],
				},
				{
					type: 'category',
					label: 'Rust',
					items: [
						{
							type: 'category',
							label: 'microde-microservice',
							link: { type: 'doc', id: 'rust-api' },
							items: [
								{
									type: 'autogenerated',
									dirName: 'rust-api-reference',
								},
							],
						},
					],
				},
			],
		},
	],
};

export default sidebars;
